
name: build and publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # We will publish new version for tag which follows 'v*.*.*' format

env:
  SERVICE_NAME: hello-world

jobs:
  publish-jar:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: make DIST jar
        run: gradlew lwjgl3:dist --no-daemon
      - name: publish jar
        run: gradlew lwjgl3:publish --no-daemon
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
